name: CLA Check

on:
  workflow_call:

jobs:
  cla:
    if: contains(fromJson('["weblate"]'), github.event.pull_request.user.login) == false
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v2
        with:
          exempted-bots: dependabot,github-actions,renovate
