name: Push (main)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    uses: ./.github/workflows/build.yaml

  release-to-charmhub:
    name: Release to CharmHub
    needs:
      - build-test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@2.6.3
        id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.6.3
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"
